name = "Neko"
license = "MIT"
min_version = "0.110.0"
description = "猫娘风格主题 - Neko Style Theme for Hugo"
tags = ["anime", "cat", "neko", "pink", "purple"]
author = "Lidure"
features = ["responsive", "particles"]